# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0

    - name: Build boostpi executable
      run: env GOOS=linux GOARCH=arm64 go build -v

    - name: Upload boostpi executable
      uses: actions/upload-artifact@v4
      with:
        name: boostpi
        path: boostpi
    
    - name: Upload boostpi config
      uses: actions/upload-artifact@v4
      with:
        name: boostpi-config.json
        path: boostpi-config.json

    - name: Upload boostpi service
      uses: actions/upload-artifact@v4
      with:
        name: boostpi.service
        path: boostpi.service
